language: go
sudo: false
go:
  - tip
os:
  - linux
install:
  - go get -u -t -v ./...
script:
  - go build -v -o bin/go-web-search
  - ./go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/ReanGD/go-web-search")
notifications:
  email:
    recipients:
      - reangd@yandex.ru
    on_success: never
    on_failure: always
